version: "3.8"

services:
  db:
    build: 
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PWD=${DB_ROOT_PWD}
        - DB_USER=${DB_USER}
        - DB_USER_PWD=${DB_USER_PWD}
    restart: on-failure
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_volume:
    driver_opts:
      type: none
      o: bind
      device : /Users/tulipe/maxperei/data/mariadb_volume
  wordpress_volume:
    driver_opts:
      type: none
      o: bind
      device: /Users/tulipe/maxperei/data/wordpress_volume