version: "3.8"

services:

  mariadb:
    container_name: my-mariadb
    networks:
      - inception
    env_file: .env
    build: 
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PWD=${DB_ROOT_PWD}
        - DB_USER=${DB_USER}
        - DB_USER_PWD=${DB_USER_PWD}
    image: my-mariadb:custom 
    restart: on-failure
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: my-wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
    env_file: .env
    environment:
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PWD=${DB_USER_PWD}
    image: my-wordpress:custom
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html/

  nginx:
    container_name: my-nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
    image: my-nginx:custom
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html/

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      type: none
      o: bind
      device : /Users/tulipe/maxperei/data/mariadb_volume
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      type: none
      o: bind
      device: /Users/tulipe/maxperei/data/wordpress_volume